services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Bogota  # Cambia esto según tu zona horaria
      - TZ=America/Bogota  # Cambia esto según tu zona horaria
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data: